version: '2'
services:
  database:
    image: mysql:5.7
    container_name: database
    volumes:
      - /opt/data/master1/dumps:/dumps:rw,cached
      - /opt/data/master1/data:/var/lib/mysql:rw,cached
      - /opt/docker/mysql-master/conf:/etc/mysql/conf.d:rw,cached
    environment:
      - MYSQL_ROOT_PASSWORD=Gotit123312##
      - MYSQL_USER=gotit_blog
      - MYSQL_PASSWORD=gotit@2019
      - MYSQL_DATABASE=gotit_blog
      - TZ=Asia/Ho_Chi_Minh
    expose:
      - "3306"
    ports:
      - "3306:3306"
    restart: always
